[package]
name = "ledger_zcash_crypto"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
#ledger_device_sdk = { version = "1.34.0", features = ["sys"] }
#ledger_device_sdk = { git = "https://github.com/Fingolfin69/ledger-device-rust-sdk.git", branch = "y333/zip32_derivation_support_build_ci_fix", features = ["sys"] }
ledger_device_sdk = { workspace = true }
pasta_curves = { version = "0.5", default-features = false }

[features]
default = ["montgomery_fallback"]

montgomery_fallback = []
